# Generated by Django 2.1.3 on 2019-01-07 14:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_pdf_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_uploader',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/jarret/Documents/Python/Projects/Personal/Personal/Home/PDF_Parser/Uploaded_Files'), upload_to=django.core.files.storage.FileSystemStorage(location='/home/jarret/Documents/Python/Projects/Personal/Personal/Home/PDF_Parser/Uploaded_Files')),
        ),
    ]
