# Generated by Django 2.1.3 on 2019-01-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20190107_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_uploader',
            name='file',
            field=models.FileField(upload_to='Media'),
        ),
    ]
