# Generated by Django 2.1.3 on 2019-01-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20190107_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_uploader',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
