# Generated by Django 2.1.3 on 2019-01-12 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20190107_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
